# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.0.10
_src_path: gh:algorandfoundation/algokit-react-frontend-template
author_email: pjguerry976@hotmail.fr
author_name: piguerry
cloud_provider: none
preset_name: production
project_name: game-frontend

