# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.14
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: pjguerry976@hotmail.fr
author_name: piguerry
cloud_provider: none
contract_name: game
deployment_language: python
preset_name: production
project_name: game

